### ISSUE TITLE
As a developer, I want to use a turnkey crypto implementation so that I can create secure, stable, and complex cryptographic functionality

### ISSUE THREAD

**Issue by mpk2** [Topl/Bifrost#13]
Ouroboros Praos requires the use of a number of new crypto types and functionality. A lot of these are compositions based on cryptographic primitives. In order to improve testability, reproducibility, and ease of use, these need to be as abstracted as possible, focusing on the ideal functionalities as defined in Ouroboros Praos's paper.

#### Sub-tasks

- [x] V-OPRF functionality (high level interface)
- [x] NIZK for equality of discrete logarithms
- [x] Group operations
- [x] Hash abstractions onto cyclic group `<g>` and binary space

**Comment by mpk2** [comment]
* Need to figure out a proper construction for a secure hash onto the cyclic group.
* Still need to organise the verification path (between Proofs/Propositions, etc.) for DiscreteLogProof 
* Need to write out the algorithm for the VRF sampling
* Maybe make a BigInt "over a group" primitive
