### ISSUE TITLE
[3pt] Research Open JSON-RPC

### ISSUE THREAD

**Issue by scasplte2** [Topl/Bifrost#254]
- [ ] Come up with plan to implement open JSON-RPC into scala
- [ ] Demo how integration with Postman will work
- [ ] Figure out if possible to more tightly couple with LokiJS & LokiPy
Focus on
- [ ] Tooling
- [ ] Capabilities

Would like to be able to generate client side libraries automatically from code

**Comment by c-georgen** [comment]
Determine whether or not this is currently worth pursuing
