### ISSUE TITLE
Evaluate the Bifrost implementation of NXT

### ISSUE THREAD

**Issue by scasplte2** [Topl/Bifrost#276]
Please read through and elucidate any differences between our version of NXT and the canonical version defined here
https://nxtdocs.jelurida.com/Nxt_Whitepaper#Cumulative_Difficulty

We might also look at the NXT code base (saw mention that it is in Java) so make sure we are doing the same steps.

- [ ] Read Nxt paper
- [ ] Evaluate Bifrost's Nxt Implementation
- [ ] Make a diagram of how Nxt works in Bifrost
