### ISSUE TITLE
Hard-fork Toplnet to Dion protocol version

### ISSUE THREAD

**Issue by scasplte2** [Topl/Bifrost#412]
- [ ] Demonstrate the fork occurring using Toplnet data by launching a node prior to the fork, querying the block data, then crossing the fork point and showing that the block data has changed.
- [ ] Make the API surface with current namespaces
- [ ] coordinate update with Suudeesh
- [ ] modify chain_replicator
- [ ] modify brambl requests
- [ ] update postman documentation
- [ ] get `dbtools` working to parse the key-value store

**Comment by scasplte2** [comment]
technically closed with the release of 1.3.3 https://github.com/Topl/Bifrost/releases/tag/v1.3.3
